services:
  app:
    build:
      context: ./app
    env_file:
      - .env
    ports:
      - "80:${APP_PORT}"
    restart: unless-stopped
    networks:
      - skeleton

networks:
  skeleton:
    driver: bridge
